name: Action CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run my own container action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@AtulJoshi'
      - name: Output the Answer
        run: echo "The Answer is ${{ steps.my-action.output.answer }}"
