name: Action CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run my own container action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@AtulJoshi'
      - name: Output the Answer
        run: echo "The Answer is ${{ steps.my-action.outputs.answer }}"
      - name: Test the Container
        if: ${{ steps.my-action.outputs.answer != 42 }}
        run: | 
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1
