# workflow to show how to develop workflow in branches
name: Develop in Branch
on:  [pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: |
            echo "workflow triggered in branch '${{ github.ref }}'"
            echo "Workflow triggered by '${{github.event_name}}'"
            echo "Workflow triggered by actor '${{github.actor}}'"
      - run: |
          echo "::debug::This is debug message"
          echo "::notice::This is notice message"
          echo "::warning::This is Warning message"
          echo "::error::This is Error message"      
      - uses: actions/checkout@v4.1.0
      - uses: devops-actions/actionlint@v0.1.2
      - run: echo "PR Title is '${{ github.event.pull_request.title }}'"
      - run: |
          echo "::notice
          file=.github/workflows/DevelopInBranch.yml,line=19,col=11,endColumn=51::There is a degub message that is not always visible!"
          echo "::warning file=.github/workflows/DevelopInBranch.yml,line=19,endline=19::A lot of messages"
          echo "::error title=Script Injection,file=.github/workflows/DevelopInBranch.yml,line=13,col=37,endColumn=68::Potential script injecton"    
          

            



