# workflow to show how to develop workflow in branches
name: Develop in Branch
on:  [pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "workflow triggered in branch '${{ github.ref }}'"
            echo "Workflow triggered by '${{github.event_name}}'"
            echo "Workflow triggered by actor '${{github.actor}}'"

            



